language: cpp

sudo: required
services:
  - docker
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-filesystem1.55-dev
      - libboost-program-options1.55-dev
      - libboost-serialization1.55-dev
      - libboost-test1.55-dev
      - libboost-regex1.55-dev
      - pandoc
env:
  global:
    - PYTHON=python CONDA_PACKAGES="numpy cython" TWINE_USERNAME=danielh
    - secure: "j8Ro21/7h5FKuJHPJRHYfOiZHMoAfD/dfpqXZreGrl79jVSEdPZmmOdvFH++CqrRdttpxOf2Lg5qOfpXfziC5ecJx1USslBSo2qwAG9JwPkwjCK7MhouM64yhVedj9Es/H635aufbyRsDIhKr5poPrrH+UebEq/63QpEdDWIWq8="
  matrix:
    - PYVER=2.7 PYNUM=2 PYTHON_INSTALL=manual
    - PYVER=2.7 PYNUM=2 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - PYVER=2.7 PYNUM=2 PYTHON_INSTALL=pip BUILD_ARCH=x86_64
    - PYVER=3.4 PYNUM=3 PYTHON_INSTALL=manual
    - PYVER=3.4 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - PYVER=3.4 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=x86_64
    - PYVER=3.5 PYNUM=3 PYTHON_INSTALL=manual
    - PYVER=3.5 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - PYVER=3.5 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=x86_64
    - PYVER=3.6 PYNUM=3 PYTHON_INSTALL=manual
    - PYVER=3.6 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - PYVER=3.6 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=x86_64
matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      env: PYVER=2.7 PYNUM=2 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - os: osx
      env: PYVER=3.4 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - os: osx
      env: PYVER=3.5 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=i686
    - os: osx
      env: PYVER=3.6 PYNUM=3 PYTHON_INSTALL=pip BUILD_ARCH=i686

before_install:
  - travis_retry .travis/install_conda.sh
  - export PATH="$PWD/miniconda/bin:$PATH"
  - source activate "$PYVER"

install:
  - travis_retry .travis/install_eigen.sh
  - export EIGEN3_INCLUDE_DIR=/usr/local/include/eigen3

before_script:
  - .travis/build_dynet.sh

after_failure:
  - cat $TRAVIS_BUILD_DIR/build/CMakeFiles/CMakeError.log

script:
  - .travis/test_dynet.sh

deploy:
  provider: script
  skip_cleanup: true
  script:
    - .travis/build_sdist.sh
    - .travis/deploy.sh
  on:
    repo: clab/dynet
    tags: true
    condition: "$PYTHON_INSTALL == pip"
